title: Mat Schaffer
email: mat@schaffer.me
description: >-
  Blog and contact information for Mat Schaffer.
baseurl: ""
url: https://matschaffer.com
twitter_username: matschaffer
github_username:  matschaffer
exclude:
  - .idea
include:
  - .well-known